/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
/* eslint-disable no-magic-numbers */

export type paths = {
    "/generate_thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Thumbnail
         * @description Generates a thumbnail from a video file using FFmpeg.
         */
        post: operations["generate_thumbnail_generate_thumbnail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe
         * @description Transcribes an audio file using Faster-Whisper.
         */
        post: operations["transcribe_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate
         * @description Translates a batch of texts using MarianMT models.
         */
        post: operations["translate_translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Filter Text
         * @description Analyzes a batch of texts using SpaCy for linguistic filtering.
         */
        post: operations["filter_text_filter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** FilterRequest */
        FilterRequest: {
            /** Texts */
            texts: string[];
            /**
             * Language
             * @default es
             */
            language: string;
        };
        /** FilterResponse */
        FilterResponse: {
            /** Results */
            results: components["schemas"]["TokenAnalysis"][][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Segment */
        Segment: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Text */
            text: string;
        };
        /** ThumbnailRequest */
        ThumbnailRequest: {
            /** File Path */
            file_path: string;
        };
        /** ThumbnailResponse */
        ThumbnailResponse: {
            /** Thumbnail Path */
            thumbnail_path: string;
        };
        /** TokenAnalysis */
        TokenAnalysis: {
            /** Text */
            text: string;
            /** Lemma */
            lemma: string;
            /** Pos */
            pos: string;
            /** Is Stop */
            is_stop: boolean;
        };
        /** TranscriptionRequest */
        TranscriptionRequest: {
            /** File Path */
            file_path: string;
            /**
             * Language
             * @default es
             */
            language: string;
        };
        /** TranscriptionResponse */
        TranscriptionResponse: {
            /** Segments */
            segments: components["schemas"]["Segment"][];
            /** Language */
            language: string;
            /** Language Probability */
            language_probability: number;
        };
        /** TranslationRequest */
        TranslationRequest: {
            /** Texts */
            texts: string[];
            /**
             * Source Lang
             * @default es
             */
            source_lang: string;
            /**
             * Target Lang
             * @default en
             */
            target_lang: string;
        };
        /** TranslationResponse */
        TranslationResponse: {
            /** Translations */
            translations: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
/* eslint-disable sonarjs/class-name */
export interface operations {
    generate_thumbnail_generate_thumbnail_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThumbnailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThumbnailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcribe_transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translate_translate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filter_text_filter_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
