#!/usr/bin/env sh
NVM_BIN="$HOME/.nvm/versions/node/$(ls -t "$HOME/.nvm/versions/node/" 2>/dev/null | head -1)/bin"
[ -d "$NVM_BIN" ] && export PATH="$NVM_BIN:$PATH"
node_modules/.bin/lint-staged --concurrent false
